### ISSUE TITLE
Can save empty inputs on analyse page

### ISSUE THREAD

**Issue by mpagels** [johnxgaehner/beatmatch-buddy#31]
The user should not be able to save empty inputs:
![Bildschirmfoto 2021-08-17 um 11 42 08](https://user-images.githubusercontent.com/54703643/129702966-b959a18c-e2fb-43dc-be31-07fe92ab35d8.png)
The image shows, just spaces

Here the collections view:
![Bildschirmfoto 2021-08-17 um 11 43 21](https://user-images.githubusercontent.com/54703643/129703253-d42d5dba-44bb-4631-869c-3890f296d403.png)

**Comment by johnxgaehner** [comment]
@mpagels, can you pls explain how have you done that?
Input should be required... haha

<img width="371" alt="Screenshot 2021-08-17 at 11 53 33" src="https://user-images.githubusercontent.com/77127212/129704935-dca92e8c-6592-48d0-9286-907b5076e069.png">

**Comment by mpagels** [comment]
I just used the `space` key to produce some spaces. ;-)
